name: Deploy to Destination Server

on:
  push:
    branches:
      - main  # Trigger this action on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the latest code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install sshpass
    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    # Step 3: Add the remote server to known_hosts
    - name: Add remote server to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.REMOTE_SERVER_IP }} >> ~/.ssh/known_hosts

    # Step 4: Ensure the destination directory exists on the remote server
    - name: Create destination directory
      run: |
        sshpass -p ${{ secrets.REMOTE_SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_IP }} 'mkdir -p /home/ubuntu/learningdosc/task-1'

    # Step 5: Copy files to the destination server using scp
    - name: Deploy files to destination server
      run: |
        sshpass -p ${{ secrets.REMOTE_SERVER_PASSWORD }} scp -r -o StrictHostKeyChecking=no ./task-1/ ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_IP }}:/home/ubuntu/learningdosc/task-1

    # Step 6: (Optional) Restart the application on the destination server
    - name: Restart FastAPI service
      run: |
        sshpass -p ${{ secrets.REMOTE_SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_IP }} 'cd /home/ubuntu/learningdosc/task-1/task-1 && sudo docker-compose down && docker-compose up -d'
