name: Deploy to Destination Server

on:
  push:
    branches:
      - main  # Trigger this action on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the latest code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install sshpass and AWS CLI
    - name: Install sshpass and AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        sudo apt-get install -y awscli

    # Step 3: Fetch GitHub IP ranges
    - name: Fetch GitHub IP ranges
      id: fetch_ips
      run: |
        curl -s https://api.github.com/meta | jq -r '.actions[]' > ip_ranges.txt

    # Step 4: Update AWS Security Group with GitHub IP ranges
    - name: Update AWS Security Group
      run: |
        for ip_range in $(cat ip_ranges.txt); do
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr $ip_range
        done
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'

    # Step 5: Add the remote server to known_hosts
    - name: Add remote server to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.REMOTE_SERVER_IP }} >> ~/.ssh/known_hosts

    # Step 6: Ensure the destination directory exists on the remote server
    - name: Create destination directory
      run: |
        sshpass -p ${{ secrets.REMOTE_SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_IP }} 'mkdir -p /home/ubuntu/learningdosc/task-1'

    # Step 7: Copy files to the destination server using scp
    - name: Deploy files to destination server
      run: |
        sshpass -p ${{ secrets.REMOTE_SERVER_PASSWORD }} scp -r -o StrictHostKeyChecking=no ./task-1/ ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_IP }}:/home/ubuntu/learningdosc/task-1

    # Step 8: (Optional) Restart the application on the destination server
    - name: Restart FastAPI service
      run: |
        sshpass -p ${{ secrets.REMOTE_SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_IP }} 'cd /home/ubuntu/learningdosc/task-1/task-1 && sudo docker-compose down && docker-compose up -d'
