name: Deploy to Destination Server

on:
  push:
    branches:
      - main  # Trigger this action on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the latest code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up AWS credentials (no need to install AWS CLI manually)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-south-1'

    # Step 3: Add public IP to AWS Security Group using a pre-built action
    - name: Add public IP to AWS security group
      uses: sohelamin/aws-security-group-add-ip-action@master
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-south-1'
        aws-security-group-id: 'sg-0cb0db06016329f94'
        port: '22'
        to-port: '22'
        protocol: 'tcp'
        description: 'GitHub Action Runner IP'

    # Step 4: Add remote server to known_hosts using a pre-built SSH action
    - name: Add remote server to known_hosts
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_SERVER_IP }}
        username: ${{ secrets.REMOTE_SERVER_USERNAME }}
        password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
        script: |
          ssh-keyscan -H ${{ secrets.REMOTE_SERVER_IP }} >> ~/.ssh/known_hosts

    # Step 5: Copy files to the remote server using SCP action
    - name: Copy files to destination server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_SERVER_IP }}
        username: ${{ secrets.REMOTE_SERVER_USERNAME }}
        password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
        source: "./task-1/"
        target: "/home/ubuntu/learningdosc/task-1"
        port: 22

    # Step 6: Restart the FastAPI application on the destination server
    - name: Restart FastAPI service on the remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_SERVER_IP }}
        username: ${{ secrets.REMOTE_SERVER_USERNAME }}
        password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
        script: |
          cd /home/ubuntu/learningdosc/task-1/task-1
          sudo docker-compose down
          sudo docker-compose up -d
