name: Deploy to Destination Server

on:
  push:
    branches:
      - main  # Trigger this action on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the latest code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up SSH to connect to the destination server
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the secret stored in GitHub

    # Step 3: Add the remote server to known_hosts
    - name: Add remote server to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 3.108.59.223 >> ~/.ssh/known_hosts

    # Step 4: Ensure the destination directory exists on the remote server
    - name: Create destination directory
      run: |
        ssh ubuntu@3.108.59.223 'mkdir -p /home/ubuntu/learningdosc/task-1'

    # Step 5: Copy files to the destination server using scp
    - name: Deploy files to destination server
      run: |
        scp -r ./task-1/ ubuntu@3.108.59.223:/home/ubuntu/learningdosc/task-1

    # Step 6: (Optional) Restart the application on the destination server
    - name: Restart FastAPI service
      run: |
        ssh ubuntu@3.108.59.223 'cd /home/ubuntu/learningdosc/task-1 && docker-compose down && docker-compose up -d'
